### ISSUE TITLE
[Doc]Create slides for ICM help session

### ISSUE THREAD

**Issue by koji** [sleepy-maker/sample_for_icm#10]
- [x] dom
~~p5serial~~
- [x] data(json/api)

- [x] video and sound

**Comment by Rushali** [comment]
where are the slides saved? can we have them in the ICM folder in the residents drive?

**Comment by koji** [comment]
@Rushali could you send me the folder link via email or slack? I will upload all slides I have.
Thanks!

**Comment by jfunky** [comment]
there's a residents drive?

**Comment by koji** [comment]
@jfunky yes, i didn't know that.
just in case send you the link. probably you can access via your nyu account
